### ISSUE TITLE
Could not load NIB in bundle

### ISSUE THREAD

**Issue by mradzinski** [sudeepjaiswal/ASJTagsView#1] opened 2016-09-30 00:11 UTC
When attempting to add a new tag I get a `Could not load NIB in bundle ... with name 'ASJTag'`

**Comment by mradzinski** [comment] 2016-09-30 00:42
Seems the XIB and the assets are not included when using the pod

**Comment by sdpjswl** [comment] 2016-09-30 08:35
![Pod content](https://cloud.githubusercontent.com/assets/8945229/18985623/65543e3c-8716-11e6-92aa-87d16db4c129.png)

I am unable to reproduce the issue. I installed the pod in a new project, the `ASJTag.xib` file downloaded, as you can see above.

Can you check if you have all the necessary files in your project? You should have the `Resources` folder with the xib and a bundle.

Also check which version of the pod you have. The latest is 1.0.

**Comment by PetrBo** [comment] 2016-10-19 17:13
The same problem here. I solved it with substitution of `[NSBundle mainBundle]` with `[NSBundle bundleForClass:[ASJTagsView class]]` in method `- (ASJTag *)tagView`.

**Comment by mradzinski** [comment] 2016-10-19 17:51
I ended up downloading the XIB from the repo and adding it manually to my project. I checked the downloaded POD and the XIB wasn't there.

**Comment by PetrBo** [comment] 2016-10-19 19:57
In my case the XIB and assets are included in downloaded pod.

**Comment by sdpjswl** [comment] 2016-10-22 04:56
Apologies for the late reply.

@mradzinski 
Perhaps it is an issue of using `resources` in the Podfile. The [official guide](http://guides.cocoapods.org/syntax/podspec.html#resource_bundles) recommends that we use `resource_bundles` instead. See [link](http://guides.cocoapods.org/syntax/podspec.html#resource_bundles). I have made a new branch 'resources' and edited the Podfile syntax. Can you test if resources download now?

@PetrBo 
Thanks for the solution, I've committed the changes and they are available in [version 1.1](https://github.com/sudeepjaiswal/ASJTagsView/releases/tag/1.1). Can you please verify that it's working?

@mradzinski 
**Update** I am unable to figure out how to test download the pod using the edited Podfile. It keeps downloading the version live on CocoaPods, even if I specify which branch to use. Any idea?

**Comment by sdpjswl** [comment] 2022-01-20 10:55
Fixed in [version 1.3](https://github.com/sdpjswl/ASJTagsView/releases/tag/1.3).

**Closed as completed by sdpjswl** 2022-01-20 10:55 UTC
